### PR TITLE
! Change null strings to null values

### PR DESCRIPTION
**Pull request by betandr**
The static JSON contains strings containing "null" which isn't a null value but rather a valid string. For parameters of the type integer this breaks unmarshalling and makes string types hard to reason about. As such I've changed the values to Python `None` types which render in JSON as `null`.

### CODE REVIEW

**Comment by Bettiher** [comment]
:shipit:

**Comment by tatiana** [comment]
@betandr do we know which part of our system injected the `"null"`s? Perhaps we need to fix the root issue somewhere else.

**Comment by Bettiher** [comment]
I think we put it manually when building the static response.

**Comment by betandr** [comment]
@tatiana I think it's just a copy-paste thing. The JSON was hand-crafted. :)

**Pull request merged**
